// <auto-generated />
using System;
using FarasaEtl.Infrastructure.Data.Target;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarasaEtl.Infrastructure.Migrations
{
    [DbContext(typeof(MonitoringBaseInfoDbContext))]
    [Migration("20241225065659_Initial-Create")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarasaEtl.Domain.Entities.Target.MarketMakingActivityLicense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BuyOrderThreshold")
                        .HasColumnType("bigint");

                    b.Property<float>("BuyRange")
                        .HasColumnType("real");

                    b.Property<short>("ContractTypeId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FarasaRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LicenseEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LicenseStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MarketMakerNationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SellOrderThreshold")
                        .HasColumnType("bigint");

                    b.Property<float>("SellRange")
                        .HasColumnType("real");

                    b.Property<long>("TradeThreshold")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MarketMakingActivityLicenses");
                });
#pragma warning restore 612, 618
        }
    }
}
